<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Nopackage"
           tests="5"
           failures="2"
           errors="0"
           skipped="3"
           time="-3214970058.466">
  <properties />
            <testcase name="initBrowser" time="7.215" classname="tests.AddInquire_Test">
                <failure type="org.openqa.selenium.WebDriverException"
                  message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:43662
Build info: version: &apos;3.141.59&apos;, revision: &apos;e82be7d358&apos;, time: &apos;2018-11-14T08:25:53&apos;
System info: host: &apos;LAPTOP-LED7K9C6&apos;, ip: &apos;192.168.137.1&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_212&apos;
Driver info: driver.version: FirefoxDriver"
              >
<![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:43662
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-LED7K9C6', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_212'
Driver info: driver.version: FirefoxDriver
  org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
  Base.BaseTest.initBrowser(BaseTest.java:25)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
  org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
  org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
  org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:43662
  okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
  okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
  okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
  okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
  okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
  okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
  okhttp3.RealCall.execute(RealCall.java:77)
  org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
  org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
  org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
  Base.BaseTest.initBrowser(BaseTest.java:25)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
  org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
  org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
  org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.ConnectException: Connection refused: connect
  java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
  java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
  java.net.AbstractPlainSocketImpl.connect(Unknown Source)
  java.net.PlainSocketImpl.connect(Unknown Source)
  java.net.SocksSocketImpl.connect(Unknown Source)
  java.net.Socket.connect(Unknown Source)
  okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
  okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
  okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
  okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
  okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
  okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
  okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
  okhttp3.RealCall.execute(RealCall.java:77)
  org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
  org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
  org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
  org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
  org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
  Base.BaseTest.initBrowser(BaseTest.java:25)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
  org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
  org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
  org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
  org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
            <testcase name="userManage" time="0.085" classname="tests.AddInquire_Test">
                <failure type="org.testng.internal.reflect.MethodMatcherException"
                  message="
[public void tests.AddInquire_Test.userManage(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: userManage([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) firstname,(java.lang.String) yingying,(java.lang.String) lastname,(java.lang.String) pei,(java.lang.String) token,(java.lang.String) 111.0,(java.lang.String) email,(java.lang.String) 652978478@qq.com,(java.lang.String) emailstatus,(java.lang.String) OK,(java.lang.String) usesleft,(java.lang.String) 1.0]"
              >
<![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void tests.AddInquire_Test.userManage(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: userManage([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) firstname,(java.lang.String) yingying,(java.lang.String) lastname,(java.lang.String) pei,(java.lang.String) token,(java.lang.String) 111.0,(java.lang.String) email,(java.lang.String) 652978478@qq.com,(java.lang.String) emailstatus,(java.lang.String) OK,(java.lang.String) usesleft,(java.lang.String) 1.0]
  org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
  org.testng.internal.Parameters.injectParameters(Parameters.java:909)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:766)
  org.testng.TestRunner.run(TestRunner.java:587)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
  org.testng.TestNG.runSuites(TestNG.java:1039)
  org.testng.TestNG.run(TestNG.java:1007)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
            <testcase name="initPage" time="0.0" classname="tests.AddInquire_Test">
          <skipped />
    </testcase>
            <testcase name="close" time="0.0" classname="tests.AddInquire_Test">
          <skipped />
    </testcase>
            <testcase name="login" time="0.0" classname="tests.AddInquire_Test">
          <skipped />
    </testcase>
  
  
</testsuite>
